### ISSUE TITLE
apparently doesn't work in mobile

### ISSUE THREAD

**Issue by viniciusf-dev** [arthcc/tech-ears#21]
i tried to use in two different models of iPhone both Safari and also Google and error that the sites return to me is always the same.

"Failed to fetch the audio."

I also think that this return can be improved and more friendly to the users.

**Comment by arthcc** [comment]
its because i used a lot of free accounts and they blocked me till I pay it for more, its 5$ if i dont find another way im gonna pay it.

**Comment by arthcc** [comment]
@ViniciusTheCoder just fixed, pls try again
