### ISSUE TITLE
line breaking in some cases

### ISSUE THREAD

**Issue by CaioHVectorA** [arthcc/tech-ears#26]
![image](https://github.com/arthcc/tech-ears/assets/109510970/9bd8cbd5-9371-49b5-91b6-28519f514d66)

Tive esse caso em específico. Sinceramente, não sei se é pelo tamanho da frase ou pelo hífen.

**Comment by arthcc** [comment]
Vou verificar se pa resolvo com regex pra validar umas coisas.

**Comment by CaioHVectorA** [comment]
Será? Não seria problema de CSS?

**Comment by arthcc** [comment]
vou dar uma olhada
