### ISSUE TITLE
Imprecision in correction when the user types an unexpected sequence of words.

### ISSUE THREAD

**Issue by CaioHVectorA** [arthcc/tech-ears#27]
![image](https://github.com/arthcc/tech-ears/assets/109510970/f8ad4cd6-431b-4747-9a88-0befb4d02289)

No exemplo acima, nota-se que ainda que eu tenha acertado uma palavra, ela não foi colorida em verde. 

## Por que isso Acontece?

```typescript
const compareAnswer = (inputValue: string, correctAnswer: string[]) => {
  const inputWords = inputValue.toLowerCase().split(" ");
  const correctWords = correctAnswer.map((word) => word.toLowerCase());
  console.log({correctWords, inputWords})
  return correctAnswer.map((word, index) => {
    if (correctWords[index] !== inputWords[index]) {
    return (
      <span key={index} className="text-red-500 ml-1">
      {word}
      </span>
    );
    } else {
    return (
      <span key={index} className="text-green-500 ml-1">
      {word}
      </span>
    );
    }
  });
  };
```

O código da função recebe uma string(que depois é transformada em array) e outra array, que depois são comparadas em conjunto utilizando o mesmo índice. Desta forma, se ocorre uma descrepância de lengths, a função já funciona incorretamente. É certo que na maioria das vezes isso não acontece, mas por exemplo, no texto: "Ensuring cross-browser compatibility" o usuário pode errar e utilizar sem o hífen, o que já provoca esse bug.

**Comment by digzom** [comment]
> ![image](https://private-user-images.githubusercontent.com/109510970/340507830-f8ad4cd6-431b-4747-9a88-0befb4d02289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NDg4NjUsIm5iZiI6MTcxODc0ODU2NSwicGF0aCI6Ii8xMDk1MTA5NzAvMzQwNTA3ODMwLWY4YWQ0Y2Q2LTQzMWItNDc0Ny05YTg4LTBiZWZiNGQwMjI4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQyMjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGRiODAyODhiYzY4MzFlZDEwMmVkZTBkMThlYTlmMjhmZWNlMjJjMGJlNzFmYWNlMTI4MjI1NGRiZTM3NjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ECS3rjeaMsZZr5WTz0sHlZodpxvVOY68XTum0MfMuFY)
> 
> No exemplo acima, nota-se que ainda que eu tenha acertado uma palavra, ela não foi colorida em verde.
> 
> ## Por que isso Acontece?
> ```ts
> const compareAnswer = (inputValue: string, correctAnswer: string[]) => {
>   const inputWords = inputValue.toLowerCase().split(" ");
>   const correctWords = correctAnswer.map((word) => word.toLowerCase());
>   console.log({correctWords, inputWords})
>   return correctAnswer.map((word, index) => {
>     if (correctWords[index] !== inputWords[index]) {
>     return (
>       <span key={index} className="text-red-500 ml-1">
>       {word}
>       </span>
>     );
>     } else {
>     return (
>       <span key={index} className="text-green-500 ml-1">
>       {word}
>       </span>
>     );
>     }
>   });
>   };
> ```
> 
> O código da função recebe uma string(que depois é transformada em array) e outra array, que depois são comparadas em conjunto utilizando o mesmo índice. Desta forma, se ocorre uma descrepância de lengths, a função já funciona incorretamente. É certo que na maioria das vezes isso não acontece, mas por exemplo, no texto: "Ensuring cross-browser compatibility" o usuário pode errar e utilizar sem o hífen, o que já provoca esse bug.

A solução me parece apenas não considerar caracteres especiais na hora de fazer a validação. Se olharmos somente as palavras para validar, para a frase "Ensuring cross-browser compatibility", ao digitar "cross-browser ensuring compatibility", vai ficar tudo verde. Acho que ainda dá pra checar por índice, só que ignorando o hífen.

Mas também há a opção de apenas criar um diff estilo "linked list" onde uma palavra aponta para a próxima e vai validando palavra à palavra, na ordem (pulando o hífen).
